### ISSUE TITLE
Archived-At header is incorrect

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/mailarch#3117]
`type_defect`   |    by lars@eggert.org

___

For the email at https://mailarchive.ietf.org/arch/msg/tsvwg/EEAZ0xXJcHzSlxbws_TiuCGSPCc/# if you look at the source, the `Archived-At` header is https://mailarchive.ietf.org/arch/msg/tsvwg/W0jZrak-6mGj7-eXXb5J3CqTWvg, which does not exist.

___
_Issue migrated from trac:3117 at 2022-03-03 14:08:53 +0000_

**Comment by rpcross** [comment]
Bad Archived-At URLs are now being redirected to the correct URL.
Fixed in this commit afaeff5402e0cfd3fa8e569e5e75b0bad3402b69
Ran "bin/scan_all.py archived_at_report --fix" to populate Redirect table.
