### ISSUE TITLE
Message plaintext unavailable 

### ISSUE THREAD

**Issue by jgscudder** [ietf-tools/mailarch#3515]
Certain messages are not readable when viewed in mailarch, see for example https://mailarchive.ietf.org/arch/msg/dyncast/tKFjRXzASMSDV2HZJknLZdQQBB8/

The message as delivered from the mailing list clearly must have been decipherable, since Joel's response quotes the plaintext, see https://mailarchive.ietf.org/arch/msg/dyncast/2kMZtgXZOthHS9F0n3As6PmmaoU/

**Comment by JaydenX31** [comment]
We

**Comment by rpcross** [comment]
This is the result of a trailing space on the Content-Transfer-Encoding = "base64 ".
Underneath we use message.get_payload(decode=True) but if the encoding is "base64 " (with space) it doesn't get decoded.

See:
https://docs.python.org/3/library/email.compat32-message.html#email.message.Message.get_payload

**Comment by rjsparks** [comment]
The original reported message was repaired. See https://mailarchive.ietf.org/arch/msg/bess/MYgJ7sFr9R-KesXK4hejis6AfIw/ for a current message showing the issue.

**Comment by rjsparks** [comment]
see https://github.com/python/cpython/issues/98188
