### ISSUE TITLE
Archived-At is not being populated with the right hash

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/mailarch#3520]
Recent example the message at
https://mailarchive.ietf.org/arch/msg/anima/HjnvBD0uZtDxrGAFdBjQP3G1QU4/
claims inside (and this is what people that were subscribed to the list would have seen):
Archived-At: <https://mailarchive.ietf.org/arch/msg/anima/NQWD8BRJEnUaE0Snq3za5DfxEec>

cc @mcr

**Comment by rpcross** [comment]
A scan of the archive shows lots of examples (~10/day) going back to 04-25-22, which corresponds to the deployment of a new IETFA server. I think it is highly likely the new server was built with pypi.org postconfirm which was never updated with the patch to fix this problem. Need to try and locate or reproduce this patch, to re-apply in production.

**Comment by rjsparks** [comment]
postconfirm at ietf-tools/github matched what was on the server at the time it was last updated.

**Comment by rpcross** [comment]
Postconfirm was re-patched to resolve this issue on 08-25-22
