### ISSUE TITLE
Search result panes not resizable on tablet

### ISSUE THREAD

**Issue by rpcross** [ietf-tools/mailarch#3610]
The search result view has two vertically stacked panes, the list pane (the list of matching messages) and the view pane (shows the contents of selected message).  The divider between these panes is draggable to allow for resizing the panes. Dragging does not work on touch screens, tablets.

**Comment by Alex200143** [comment]
![Uploading feed-icon-16x16.jpg…]()

**Comment by Alex200143** [comment]
```javascript
@kesara 
![lock-icon](https://github.com/ietf-tools/mailarch/assets/108958915/655d702e-029c-4b68-bc07-034187cd00da)
#3615 
```
