### ISSUE TITLE
Thread view is broken

### ISSUE THREAD

**Issue by mjoras** [ietf-tools/mailarch#3625]
It seems as though the thread view is currently borked. Every link is currently being treated as a leaf with no view "down".

E.g. [this link](https://mailarchive.ietf.org/arch/msg/quic/M9pkSGzTSHunNC1yeySaB3irCVo/) appears as if it is a single message in a thread, but it's not.

<img width="502" alt="image" src="https://github.com/ietf-tools/mailarch/assets/6666676/3b11d2d3-ca76-424c-9c77-4fde8caf5a0a">

Going back we see [there's a thread](https://mailarchive.ietf.org/arch/msg/quic/9PPpO-5lcgx_Jppz2lAasG1oPR0/), and if you click on one of those you get a larger but still partial tree, unless you are at the true leaf.
<img width="579" alt="image" src="https://github.com/ietf-tools/mailarch/assets/6666676/1f831950-1419-4a7a-b234-258aba1f1865">

This makes the thread navigation functionally useless.

**Comment by rjsparks** [comment]
To help with triage - this is what that particular set of messages looks like in a threaded-view in Thunderbird via imap access to the archive:
<img width="1527" alt="image" src="https://github.com/ietf-tools/mailarch/assets/10996692/4d5dea32-2c66-40d9-9f71-061a9a3a363d">

**Comment by rjsparks** [comment]
@mjoras - This particular example now works. Are you still encountering this in other (should be) threads?
If not, we'll close this as OBE.
